version: '3.8'

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb1:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - 27018:27017
    volumes:
      - ./data/mongodb2:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongodb1:
  mongodb2:
